from __future__ import annotations

from .schemas import (
    AgentRequest,
    CompanyProfile,
    DemandSignal,
    Incident,
    InventoryItem,
    PurchaseOrder,
    SupplierRecord,
)


def build_demo_request() -> AgentRequest:
    return AgentRequest(
        company=CompanyProfile(
            company_name="Arcforge Engineering",
            sector="Power Systems EPC",
            active_projects=6,
            planner_horizon_days=90,
            target_service_level_pct=98.0,
        ),
        suppliers=[
            SupplierRecord(
                name="Helios Cast & Forge",
                category="Forged valves",
                country="India",
                lead_time_days=42,
                on_time_delivery_pct=88.0,
                quality_ppm=1800,
                annual_spend_usd=740000.0,
                approved_alternatives=0,
                risk_flags=["single source", "late NCR closure"],
            ),
            SupplierRecord(
                name="BluePeak Controls",
                category="PLC and control panels",
                country="Germany",
                lead_time_days=55,
                on_time_delivery_pct=93.0,
                quality_ppm=650,
                annual_spend_usd=1280000.0,
                approved_alternatives=1,
                risk_flags=["port congestion"],
            ),
            SupplierRecord(
                name="Copperline Metals",
                category="Copper busbars",
                country="Malaysia",
                lead_time_days=28,
                on_time_delivery_pct=97.0,
                quality_ppm=300,
                annual_spend_usd=510000.0,
                approved_alternatives=2,
                risk_flags=[],
            ),
            SupplierRecord(
                name="Kerala Forge Works",
                category="Forged valves",
                country="India",
                lead_time_days=56,
                on_time_delivery_pct=91.0,
                quality_ppm=1400,
                annual_spend_usd=180000.0,
                approved_alternatives=1,
                risk_flags=["capacity constrained"],
            ),
            SupplierRecord(
                name="Mitsuba Automation",
                category="PLC and control panels",
                country="Japan",
                lead_time_days=62,
                on_time_delivery_pct=96.0,
                quality_ppm=420,
                annual_spend_usd=320000.0,
                approved_alternatives=2,
                risk_flags=[],
            ),
            SupplierRecord(
                name="Delhi Metals Co",
                category="Copper busbars",
                country="India",
                lead_time_days=24,
                on_time_delivery_pct=94.0,
                quality_ppm=520,
                annual_spend_usd=210000.0,
                approved_alternatives=1,
                risk_flags=["new supplier"],
            ),
        ],
        inventory=[
            InventoryItem(
                sku="VALVE-16-A105",
                description="16 inch forged gate valve",
                category="Forged valves",
                supplier_name="Helios Cast & Forge",
                on_hand_qty=18,
                reorder_point_qty=24,
                safety_stock_qty=14,
                daily_demand_qty=0.9,
                lead_time_days=42,
                unit_cost_usd=3850.0,
                criticality="mission-critical",
            ),
            InventoryItem(
                sku="PLC-S7-IO48",
                description="PLC I/O module 48 point",
                category="Automation",
                supplier_name="BluePeak Controls",
                on_hand_qty=21,
                reorder_point_qty=18,
                safety_stock_qty=12,
                daily_demand_qty=0.7,
                lead_time_days=55,
                unit_cost_usd=2250.0,
                criticality="high",
            ),
            InventoryItem(
                sku="BUSBAR-CU-40",
                description="Copper busbar 40 mm",
                category="Electrical",
                supplier_name="Copperline Metals",
                on_hand_qty=220,
                reorder_point_qty=160,
                safety_stock_qty=90,
                daily_demand_qty=4.0,
                lead_time_days=28,
                unit_cost_usd=92.0,
                criticality="high",
            ),
        ],
        purchase_orders=[
            PurchaseOrder(
                po_number="PO-24017",
                supplier_name="Helios Cast & Forge",
                sku="VALVE-16-A105",
                quantity=30,
                due_in_days=19,
                value_usd=115500.0,
                status="delayed",
                expedite_possible=True,
            ),
            PurchaseOrder(
                po_number="PO-24028",
                supplier_name="BluePeak Controls",
                sku="PLC-S7-IO48",
                quantity=16,
                due_in_days=34,
                value_usd=36000.0,
                status="in_transit",
                expedite_possible=False,
            ),
            PurchaseOrder(
                po_number="PO-24044",
                supplier_name="Copperline Metals",
                sku="BUSBAR-CU-40",
                quantity=140,
                due_in_days=12,
                value_usd=12880.0,
                status="released",
                expedite_possible=True,
            ),
        ],
        demand_signals=[
            DemandSignal(
                sku="VALVE-16-A105",
                next_30_day_demand_qty=35,
                next_90_day_demand_qty=82,
                confidence_pct=81.0,
            ),
            DemandSignal(
                sku="PLC-S7-IO48",
                next_30_day_demand_qty=14,
                next_90_day_demand_qty=38,
                confidence_pct=74.0,
            ),
            DemandSignal(
                sku="BUSBAR-CU-40",
                next_30_day_demand_qty=110,
                next_90_day_demand_qty=290,
                confidence_pct=79.0,
            ),
        ],
        incidents=[
            Incident(
                title="Valve body machining NCR still open",
                severity="high",
                supplier_name="Helios Cast & Forge",
                sku="VALVE-16-A105",
                description="Dimensional deviation on the last incoming batch is still under supplier review.",
                days_open=8,
            ),
            Incident(
                title="Hamburg port congestion affecting controls shipment",
                severity="medium",
                supplier_name="BluePeak Controls",
                sku="PLC-S7-IO48",
                description="Forwarder expects a 5 to 7 day delay on vessel unloading and customs clearance.",
                days_open=3,
            ),
        ],
        ask="Which materials threaten project delivery, and what actions should procurement and planning take this week?",
    )
